---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db1
  name: db1
  namespace: {{ .Values.platomics.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db1
  template:
    metadata:
      labels:
        app: db1
    spec:
      containers:
      - image: nginx:1.16.1-alpine
        imagePullPolicy: IfNotPresent
        name: nginx
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db1
  name: db1
  namespace: {{ .Values.platomics.namespace | quote }}
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 80
  selector:
    app: db1