---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db2
  name: db2
  namespace: {{ .Values.platomics.namespace | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db2
  template:
    metadata:
      labels:
        app: db2
    spec:
      containers:
      - env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              key: username
              name: database-secret
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: database-secret
        image: nginx:1.16.1-alpine
        name: nginx
        resources: {}            
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db2
  name: db2
  namespace: {{ .Values.platomics.namespace | quote }}
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 80
  selector:
    app: db2