apiVersion: v1
kind: Secret
metadata:
  name: database-secret
  namespace: {{ .Values.platomics.namespace | quote }}
stringData:
  password: {{ .Values.platomics.db.password | quote }}
  username: {{ .Values.platomics.db.username | quote  }}